---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mochi-deployment
  labels:
    app: mochi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mochi
  template:
    metadata:
      labels:
        app: mochi
    spec:
      runtimeClassName: nvidia
      containers:
      - name: mochi
        image: r8.im/genmoai/mochi-1@sha256:1944af04d098ef69bed7f9d335d102e652203f268ec4aaa2d836f6217217e460
        resources:
          limits:
            nvidia.com/gpu: "4"           # required to allocate 4 GPUs
            cpu: "60"                    # optional: max 60 CPUs
            memory: "450Gi"
          requests:
            nvidia.com/gpu: "4"           # GPU requests must match limits for now
            cpu: "50"                    # optional: guaranteed 50 CPUs
            memory: "350Gi"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mochi-service
  labels:
    app: mochi
spec:
  selector:
    app: mochi
  ports:
  - port: 5000
    targetPort: 5000
    name: mochi
  type: ClusterIP
